[package]
name = "json"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "staticlib" ]

[dependencies]
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
